### ISSUE TITLE
running image with LOCAL_GRP_ID=0 fails

### ISSUE THREAD

**Issue by blbradley** [ZencashOfficial/zen-node-docker#5] opened 2018-04-07 16:32 UTC
```
$ docker run --name zend-group-check -d -e LOCAL_USER_ID=0 -e LOCAL_GRP_ID=0 -v /etc/letsencrypt:/etc/letsencrypt zencash/zen-node
3515ded8e9e301d63430d5e46d5255367c3a7fdf919f157265631b47e3ad937b
$ docker logs zend-group-check
groupadd: GID '0' already exists
```

**Comment by cronicc** [comment] 2019-05-10 16:55
Well, this is kind of by design (image is not intended to be run as root). See e.g. https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b , but I see your point. We could certainly modify entrypoint.sh to allow running as root.

**Comment by cronicc** [comment] 2019-07-18 22:56
Addressed in https://github.com/ZencashOfficial/zen-node-docker/pull/14

**Closed by cronicc** 2019-07-18 22:56 UTC
